package cha.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

// AI-Assisted: This JavaDoc comment was generated by ChatGPT.
/**
 * A UI component that represents a single dialog message in the chat window.
 * <p>
 * Each {@code DialogBox} consists of:
 * <ul>
 * <li>A {@link Label} containing the dialog text</li>
 * <li>An {@link ImageView} representing the speaker's avatar</li>
 * </ul>
 * The layout can be flipped to distinguish between user messages
 * and chatbot messages.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;

    @FXML
    private ImageView displayPicture;

    // AI-Assisted: This JavaDoc comment was generated by ChatGPT.
    /**
     * Creates a {@code DialogBox} with the specified text and image.
     *
     * @param text The message to display.
     * @param img  The avatar image of the speaker.
     * @throws IllegalStateException if the FXML file cannot be loaded.
     */
    private DialogBox(String text, Image img) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }

        dialog.setText(text);
        displayPicture.setImage(img);
    }

    // AI-Assisted: This JavaDoc comment was generated by ChatGPT.
    /**
     * Reverses the position of the dialog components.
     * <p>
     * After flipping:
     * <ul>
     * <li>The avatar appears on the left</li>
     * <li>The text appears on the right</li>
     * </ul>
     * This is used to visually distinguish chatbot messages from user messages.
     */
    private void flip() {
        ObservableList<Node> tmp = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(tmp);
        getChildren().setAll(tmp);
        setAlignment(Pos.TOP_LEFT);
    }

    // AI-Assisted: This JavaDoc comment was generated by ChatGPT.
    /**
     * Creates a dialog box representing a user message.
     *
     * @param text The user's message.
     * @param img  The user's avatar image.
     * @return A {@code DialogBox} aligned for user display.
     */
    public static DialogBox getUserDialog(String text, Image img) {
        return new DialogBox(text, img);
    }

    // AI-Assisted: This JavaDoc comment was generated by ChatGPT.
    /**
     * Creates a dialog box representing a chatbot message.
     * The dialog box is flipped to visually distinguish it from user messages.
     *
     * @param text The chatbot's message.
     * @param img  The chatbot's avatar image.
     * @return A flipped {@code DialogBox} aligned for chatbot display.
     */
    public static DialogBox getChaDialog(String text, Image img) {
        var db = new DialogBox(text, img);
        db.flip();
        return db;
    }
}
